package ztk.compressedblocks;

import net.minecraft.block.Block;
import net.minecraft.block.material.MapColor;
import net.minecraft.block.material.Material;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.Item;
import net.minecraftforge.common.config.Configuration;
import cpw.mods.fml.client.registry.RenderingRegistry;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.registry.EntityRegistry;
import cpw.mods.fml.common.registry.GameRegistry;

@Mod(modid = Core.modid, name = "Compressed Blocks", version = "1.0.0.0")

public class Core
{
	public static final String modid = "compressedblocks";
	
	private final String type[] = {null, "lc", "mc", "hc"};
	private final int type_num[] = {0, 1, 2, 3};
	
	public static boolean ConfigCraftingLCB;
	public static boolean ConfigCraftingMCB;
	public static boolean ConfigCraftingHCB;
	
	public static int ConfigUnCraftingLCB;
	public static int ConfigUnCraftingMCB;
	public static int ConfigUnCraftingHCB;

	@EventHandler
	public void preInit(FMLPreInitializationEvent Event)
	{
		/** Configuration file */
		Configuration config = new Configuration(Event.getSuggestedConfigurationFile());
		config.load();
		
        ConfigCraftingLCB = config.get(Configuration.CATEGORY_GENERAL, "1|Low compressed", true, "Crafting Compressed blocks.").getBoolean(true);
        ConfigCraftingMCB = config.get(Configuration.CATEGORY_GENERAL, "2|Medium compressed", true).getBoolean(true);
        ConfigCraftingHCB = config.get(Configuration.CATEGORY_GENERAL, "3|High compressed", true).getBoolean(true);
        
        ConfigUnCraftingLCB = config.get(Configuration.CATEGORY_GENERAL, "4|Low compressed", 1, "Uncrafting Compressed blocks." + config.NEW_LINE + "How many buckets to use?" + config.NEW_LINE + "-1 : recipe unavailable" + config.NEW_LINE + "0/1/2/4/8 : available").getInt();
        ConfigUnCraftingMCB = config.get(Configuration.CATEGORY_GENERAL, "5|Medium compresse", 4).getInt();
        ConfigUnCraftingHCB = config.get(Configuration.CATEGORY_GENERAL, "6|High compresse", 8).getInt();
		
		config.save();
		
		/** Name of items */
		String low_adhesive = "low_adhesive";
		String medium_adhesive = "medium_adhesive";
		String little_medium_adhesive = "little_medium_adhesive";
		String very_medium_adhesive = "very_medium_adhesive";
		String high_magma_cream = "high_magma_cream";
		String high_ender_pearl = "high_ender_pearl";
		String high_adhesive = "high_adhesive";
		String little_high_adhesive = "little_high_adhesive";
		String slime_cream = "slime_cream";
		String very_high_adhesive = "very_high_adhesive";
		
		/** New creative tab for items */
		CreativeTabs tab_compressed_blocks = new CreativeTabs("tab_compressed_blocks")
		{
			public Item getTabIconItem()
			{
				return GameRegistry.findItem(modid, "slime_cream");
			}
		};
		
		/** Registration items */
		GameRegistry.registerItem((new ItemCompressed(1)).setUnlocalizedName(low_adhesive).setCreativeTab(tab_compressed_blocks).setTextureName(modid + ":" + low_adhesive), low_adhesive);
		GameRegistry.registerItem((new ItemCompressed(2)).setUnlocalizedName(medium_adhesive).setCreativeTab(tab_compressed_blocks).setTextureName(modid + ":" + medium_adhesive), medium_adhesive);
		GameRegistry.registerItem((new ItemCompressed(2)).setUnlocalizedName(little_medium_adhesive).setCreativeTab(tab_compressed_blocks).setTextureName(modid + ":" + little_medium_adhesive), little_medium_adhesive);
		GameRegistry.registerItem((new ItemCompressed(2)).setUnlocalizedName(very_medium_adhesive).setCreativeTab(tab_compressed_blocks).setTextureName(modid + ":" + very_medium_adhesive), very_medium_adhesive);
		GameRegistry.registerItem((new ItemCompressed(3)).setUnlocalizedName(high_magma_cream).setCreativeTab(tab_compressed_blocks).setTextureName(modid + ":" + high_magma_cream), high_magma_cream);
		GameRegistry.registerItem((new ItemCompressed(3)).setUnlocalizedName(high_ender_pearl).setCreativeTab(tab_compressed_blocks).setTextureName(modid + ":" + high_ender_pearl), high_ender_pearl);
		GameRegistry.registerItem((new ItemCompressed(3)).setUnlocalizedName(high_adhesive).setCreativeTab(tab_compressed_blocks).setTextureName(modid + ":" + high_adhesive), high_adhesive);
		GameRegistry.registerItem((new ItemCompressed(3)).setUnlocalizedName(little_high_adhesive).setCreativeTab(tab_compressed_blocks).setTextureName(modid + ":" + little_high_adhesive), little_high_adhesive);
		GameRegistry.registerItem((new ItemCompressed(3)).setUnlocalizedName(slime_cream).setCreativeTab(tab_compressed_blocks).setTextureName(modid + ":" + slime_cream), slime_cream);
		GameRegistry.registerItem((new ItemCompressed(3)).setUnlocalizedName(very_high_adhesive).setCreativeTab(tab_compressed_blocks).setTextureName(modid + ":" + very_high_adhesive), very_high_adhesive);
		
		/** Name of blocks */
		String bedrock = "bedrock";
		String stonebrick = "stonebrick";
		String stone = "stone";
		String cobblestone[] = {"cobblestone", "stonebrick"};
		String cobblestone_mossy[] = {"mossy_cobblestone", "stoneMoss", "cobblestone_mossy"};
		String gravel = "gravel";
		String dirt = "dirt";
		String sand = "sand";
		String sandstone[] = {"sandstone", "sandStone"};
		String end_stone[] = {"end_stone", "whiteStone"};
		String sponge = "sponge";
		String wood[] = {"wood", "planks"};
		String bookshelf = "bookshelf";
		String log = "log";
		String pumpkin = "pumpkin";
		String melon = "melon";
		String glass = "glass";
		String stained_glass[] = {"stained_glass", "stainedGlass", "glass"};
		String wool[] = {"wool", "cloth"};
		String tnt = "tnt";
		String redstone_lamp[] = {"redstone_lamp", "redstoneLight"};
		String glowstone[] = {"glowstone", "lightgem"};
		String soul_sand[] = {"soul_sand", "hellsand"};
		String obsidian = "obsidian";
		String nether_brick[] = {"nether_brick", "netherBrick"};
		String netherrack[] = {"netherrack", "hellrock"};
		String quartz_ore[] = {"quartz_ore", "netherquartz"};
		String quartz_block[] = {"quartz_block", "quartzBlock"};
		String snow = "snow";
		String ice = "ice";
		String ice_packed[] = {"packed_ice", "icePacked", "ice_packed"};
		String clay = "clay";
		String hardened_clay[] = {"hardened_clay", "clayHardened"};
		String hardened_clay_stained[] = {"hardened_clay_stained", "clayHardenedStained", "stained_hardened_clay"};
		String brick = "brick";
		String coal_block[] = {"coal_block", "blockCoal"};
		String iron_block[] = {"iron_block", "blockIron"};
		String gold_block[] = {"gold_block", "blockGold"};
		String diamond_block[] = {"diamond_block", "blockDiamond"};
		String lapis_block[] = {"lapis_block", "blockLapis"};
		String emerald_block[] = {"emerald_block", "blockEmerald"};
		String redstone_block[] = {"redstone_block", "blockRedstone"};
		String coal_ore[] = {"coal_ore", "oreCoal"};
		String iron_ore[] = {"iron_ore", "oreIron"};
		String gold_ore[] = {"gold_ore", "oreGold"};
		String diamond_ore[] = {"diamond_ore", "oreDiamond"};
		String lapis_ore[] = {"lapis_ore", "oreLapis"};
		String emerald_ore[] = {"emerald_ore", "oreEmerald"};
		String redstone_ore[] = {"redstone_ore", "oreRedstone"};
		
		/** New creative tab for low compressed blocks */
		CreativeTabs tab_lc_block = new CreativeTabs("tab_" + type[1] + "_blocks")
		{
			public Item getTabIconItem()
			{
				return Item.getItemFromBlock(GameRegistry.findBlock(modid, type[1] + "_blockIron"));
			}
		};
		
		/** Registration low compressed blocks */
		GameRegistry.registerBlock((new BlockCompressed(type_num[1], bedrock, Material.rock)).setCreativeTab(tab_lc_block).setBlockUnbreakable().setResistance((float) (Math.pow(8, type_num[1]) * 6000000.0F)).setStepSound(Block.soundTypePiston).setBlockName(bedrock).setBlockTextureName(modid + ":" + type[1] + "/" + bedrock), ItemBlockCompressed.class, type[1] + "_" + bedrock);
		GameRegistry.registerBlock((new BlockCompressedStoneBrick(type_num[1], stonebrick)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 1.5F)).setResistance((float) (Math.pow(8, type_num[1]) * 10.0F)).setStepSound(Block.soundTypePiston).setBlockName(stonebrick + "smooth").setBlockTextureName(modid + ":" + type[1] + "/" + stonebrick), ItemBlockCompressedWithMetadata.class, type[1] + "_" + stonebrick + "smooth");
		GameRegistry.registerBlock((new BlockCompressedStone(type_num[1], stone, Material.rock)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 1.5F)).setResistance((float) (Math.pow(8, type_num[1]) * 10.0F)).setStepSound(Block.soundTypePiston).setBlockName(stone).setBlockTextureName(modid + ":" + type[1] + "/" + stone), ItemBlockCompressed.class, type[1] + "_" + stone);
		GameRegistry.registerBlock((new BlockCompressed(type_num[1], cobblestone[0], Material.rock)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 2.0F)).setResistance((float) (Math.pow(8, type_num[1]) * 80.0F)).setStepSound(Block.soundTypePiston).setBlockName(cobblestone[1]).setBlockTextureName(modid + ":" + type[1] + "/" + cobblestone[0]), ItemBlockCompressed.class, type[1] + "_" + cobblestone[1]);
		GameRegistry.registerBlock((new BlockCompressed(type_num[1], cobblestone_mossy[0], Material.rock)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 2.0F)).setResistance((float) (Math.pow(8, type_num[1]) * 10.0F)).setStepSound(Block.soundTypePiston).setBlockName(cobblestone_mossy[1]).setBlockTextureName(modid + ":" + type[1] + "/" + cobblestone_mossy[2]), ItemBlockCompressed.class, type[1] + "_" + cobblestone_mossy[1]);
		GameRegistry.registerBlock((new BlockCompressedGravel(type_num[1], gravel)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 0.6F)).setStepSound(Block.soundTypeGravel).setBlockName(gravel).setBlockTextureName(modid + ":" + type[1] + "/" + gravel), ItemBlockCompressed.class, type[1] + "_" + gravel);
		GameRegistry.registerBlock((new BlockCompressedDirt(type_num[1], dirt, Material.ground)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 0.5F)).setStepSound(Block.soundTypeGravel).setBlockName(dirt + ".default").setBlockTextureName(modid + ":" + type[1] + "/" + dirt), ItemBlockCompressed.class, type[1] + "_" + dirt + ".default");
		GameRegistry.registerBlock((new BlockCompressedSand(type_num[1], modid + ":" + type[1] + "/")).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 0.5F)).setStepSound(Block.soundTypeSand).setBlockName(sand).setBlockTextureName(modid + ":" + type[1] + "/" + sand), ItemBlockCompressedWithMetadata.class, type[1] + "_" + sand);
		GameRegistry.registerBlock((new BlockCompressedSandStone(type_num[1], sandstone[0], Material.rock)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 0.8F)).setStepSound(Block.soundTypePiston).setBlockName(sandstone[1]).setBlockTextureName(modid + ":" + type[1] + "/" + sandstone[0]), ItemBlockCompressedWithMetadata.class, type[1] + "_" + sandstone[1]);
		GameRegistry.registerBlock((new BlockCompressed(type_num[1], end_stone[0], Material.rock)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 3.0F)).setResistance((float) (Math.pow(8, type_num[1]) * 15.0F)).setStepSound(Block.soundTypePiston).setBlockName(end_stone[1]).setBlockTextureName(modid + ":" + type[1] + "/" + end_stone[0]), ItemBlockCompressed.class, type[1] + "_" + end_stone[1]);
		GameRegistry.registerBlock((new BlockCompressedWood(type_num[1], wood[1])).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 2.0F)).setResistance((float) (Math.pow(8, type_num[1]) * 5.0F)).setStepSound(Block.soundTypeWood).setBlockName(wood[0]).setBlockTextureName(modid + ":" + type[1] + "/" + wood[1]), ItemBlockCompressedWithMetadata.class, type[1] + "_" + wood[0]);
		GameRegistry.registerBlock((new BlockCompressedBookshelf(type_num[1], bookshelf, Material.wood)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 1.5F)).setStepSound(Block.soundTypeWood).setBlockName(bookshelf).setBlockTextureName(modid + ":" + type[1] + "/" + bookshelf), ItemBlockCompressed.class, type[1] + "_" + bookshelf);
		GameRegistry.registerBlock((new BlockCompressedOldLog(type_num[1], log, Material.wood)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 2.0F)).setStepSound(Block.soundTypeWood).setBlockName(log).setBlockTextureName(modid + ":" + type[1] + "/" + log), ItemBlockCompressedWithMetadata.class, type[1] + "_" + log);
		GameRegistry.registerBlock((new BlockCompressedNewLog(type_num[1], log + "2", Material.wood)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 2.0F)).setStepSound(Block.soundTypeWood).setBlockName(log).setBlockTextureName(modid + ":" + type[1] + "/" + log), ItemBlockCompressedWithMetadata.class, type[1] + "_" + log + "2");
		GameRegistry.registerBlock((new BlockCompressedPumpkin(type_num[1], pumpkin, Material.gourd, false)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 1.0F)).setStepSound(Block.soundTypeWood).setBlockName(pumpkin).setBlockTextureName(modid + ":" + type[1] + "/" + pumpkin), ItemBlockCompressed.class, type[1] + "_" + pumpkin);
		GameRegistry.registerBlock((new BlockCompressedPumpkin(type_num[1], "lit_" + pumpkin, Material.gourd, true)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 1.0F)).setLightLevel(1.0F).setStepSound(Block.soundTypeWood).setBlockName("lit" + pumpkin).setBlockTextureName(modid + ":" + type[1] + "/" + pumpkin), ItemBlockCompressed.class, type[1] + "_lit" + pumpkin);
		GameRegistry.registerBlock((new BlockCompressedMelon(type_num[1], melon, Material.gourd)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 1.0F)).setStepSound(Block.soundTypeWood).setBlockName(melon).setBlockTextureName(modid + ":" + type[1] + "/" + melon), ItemBlockCompressed.class, type[1] + "_" + melon);
		GameRegistry.registerBlock((new BlockCompressedSponge(type_num[1], sponge, Material.sponge)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 0.6F)).setStepSound(Block.soundTypeGrass).setBlockName(sponge).setBlockTextureName(modid + ":" + type[1] + "/" + sponge), ItemBlockCompressed.class, type[1] + "_" + sponge);
		GameRegistry.registerBlock((new BlockCompressedGlass(type_num[1], modid + ":" + type[1] + "/" + glass, Material.glass, false)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 0.3F)).setStepSound(Block.soundTypeGlass).setBlockName(glass).setBlockTextureName(modid + ":" + type[1] + "/" + glass), ItemBlockCompressed.class, type[1] + "_" + glass);
		GameRegistry.registerBlock((new BlockCompressedStainedGlass(type_num[1], stained_glass[2], Material.glass)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 0.3F)).setStepSound(Block.soundTypeGlass).setBlockName(stained_glass[1]).setBlockTextureName(modid + ":" + type[1] + "/" + stained_glass[2]), ItemBlockCompressedWithMetadata.class, type[1] + "_" + stained_glass[1]);
		GameRegistry.registerBlock((new BlockCompressedWool(type_num[1], wool[0], Material.cloth)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 0.6F)).setStepSound(Block.soundTypeCloth).setBlockName(wool[1]).setBlockTextureName(modid + ":" + type[1] + "/" + wool[0] + "_colored"), ItemBlockCompressedWithMetadata.class, type[1] + "_" + wool[1]);
		GameRegistry.registerBlock((new BlockCompressedTNT(type_num[1], tnt, Material.tnt)).setCreativeTab(tab_lc_block).setHardness(0.0F).setStepSound(Block.soundTypeGrass).setBlockName(tnt).setBlockTextureName(modid + ":" + type[1] + "/" + tnt), ItemBlockCompressed.class, type[1] + "_" + tnt);
		GameRegistry.registerBlock((new BlockCompressedRedstoneLight(type_num[1], redstone_lamp[0], Material.redstoneLight, false)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 0.3F)).setStepSound(Block.soundTypeGlass).setBlockName(redstone_lamp[1]).setBlockTextureName(modid + ":" + type[1] + "/" + redstone_lamp[0] + "_off"), ItemBlockCompressed.class, type[1] + "_" + redstone_lamp[1]);
		GameRegistry.registerBlock((new BlockCompressedRedstoneLight(type_num[1], "lit_" + redstone_lamp[0], Material.redstoneLight, true)).setHardness((float) (Math.pow(8, type_num[1]) * 0.3F)).setStepSound(Block.soundTypeGlass).setBlockName(redstone_lamp[1]).setBlockTextureName(modid + ":" + type[1] + "/" + redstone_lamp[0] + "_on"), ItemBlockCompressed.class, type[1] + "_lit_" + redstone_lamp[1]);
		GameRegistry.registerBlock((new BlockCompressedGlowstone(type_num[1], glowstone[0], Material.glass)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 0.3F)).setStepSound(Block.soundTypeGlass).setLightLevel(1.0F).setBlockName(glowstone[1]).setBlockTextureName(modid + ":" + type[1] + "/" + glowstone[0]), ItemBlockCompressed.class, type[1] + "_" + glowstone[1]);
		GameRegistry.registerBlock((new BlockCompressedSoulSand(type_num[1], soul_sand[0], Material.sand)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 0.5F)).setStepSound(Block.soundTypeSand).setBlockName(soul_sand[1]).setBlockTextureName(modid + ":" + type[1] + "/" + soul_sand[0]), ItemBlockCompressed.class, type[1] + "_" + soul_sand[1]);
		GameRegistry.registerBlock((new BlockCompressedObsidian(type_num[1], obsidian, Material.rock)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 50.0F)).setResistance((float) (Math.pow(8, type_num[1]) * 2000.0F)).setStepSound(Block.soundTypePiston).setBlockName(obsidian).setBlockTextureName(modid + ":" + type[1] + "/" + obsidian), ItemBlockCompressed.class, type[1] + "_" + obsidian);
		GameRegistry.registerBlock((new BlockCompressed(type_num[1], nether_brick[0], Material.rock)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 2.0F)).setResistance((float) (Math.pow(8, type_num[1]) * 10.0F)).setStepSound(Block.soundTypePiston).setBlockName(nether_brick[1]).setBlockTextureName(modid + ":" + type[1] + "/" + nether_brick[0]), ItemBlockCompressed.class, type[1] + "_" + nether_brick[1]);
		GameRegistry.registerBlock((new BlockCompressedNetherrack(type_num[1], netherrack[0], Material.rock)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 0.4F)).setStepSound(Block.soundTypePiston).setBlockName(netherrack[1]).setBlockTextureName(modid + ":" + type[1] + "/" + netherrack[0]), ItemBlockCompressed.class, type[1] + "_" + netherrack[1]);
		GameRegistry.registerBlock((new BlockCompressedOre(type_num[1], quartz_ore[0], Material.rock)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 3.0F)).setResistance((float) (Math.pow(8, type_num[1]) * 5.0F)).setStepSound(Block.soundTypePiston).setBlockName(quartz_ore[1]).setBlockTextureName(modid + ":" + type[1] + "/" + quartz_ore[0]), ItemBlockCompressed.class, type[1] + "_" + quartz_ore[1]);
		GameRegistry.registerBlock((new BlockCompressedQuartz(type_num[1], quartz_block[0], Material.rock)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 0.8F)).setStepSound(Block.soundTypePiston).setBlockName(quartz_block[1]).setBlockTextureName(modid + ":" + type[1] + "/" + quartz_block[0]), ItemBlockCompressedWithMetadata.class, type[1] + "_" + quartz_block[1]);
		GameRegistry.registerBlock((new BlockCompressedSnowBlock(type_num[1], snow, Material.craftedSnow)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 0.2F)).setStepSound(Block.soundTypeSnow).setBlockName(snow).setBlockTextureName(modid + ":" + type[1] + "/" + snow), ItemBlockCompressed.class, type[1] + "_" + snow);
		GameRegistry.registerBlock((new BlockCompressedIce(type_num[1], modid + ":" + type[1] + "/" + ice, Material.ice)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 0.5F)).setLightOpacity(6 - type_num[1] * 2).setStepSound(Block.soundTypeGlass).setBlockName(ice).setBlockTextureName(modid + ":" + type[1] + "/" + ice), ItemBlockCompressed.class, type[1] + "_" + ice);
		GameRegistry.registerBlock((new BlockCompressedPackedIce(type_num[1],ice_packed[0], Material.packedIce)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 0.5F)).setStepSound(Block.soundTypeGlass).setBlockName(ice_packed[1]).setBlockTextureName(modid + ":" + type[1] + "/" + ice_packed[2]), ItemBlockCompressed.class, type[1] + "_" + ice_packed[1]);
		GameRegistry.registerBlock((new BlockCompressedClay(type_num[1], clay, Material.clay)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 0.6F)).setStepSound(Block.soundTypeGravel).setBlockName(clay).setBlockTextureName(modid + ":" + type[1] + "/" + clay), ItemBlockCompressed.class, type[1] + "_" + clay);
		GameRegistry.registerBlock((new BlockCompressedClayHardened(type_num[1], hardened_clay[0], Material.rock)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 1.25F)).setResistance((float) (Math.pow(8, type_num[1]) * 7.0F)).setStepSound(Block.soundTypePiston).setBlockName(hardened_clay[1]).setBlockTextureName(modid + ":" + type[1] + "/" + hardened_clay[0]), ItemBlockCompressed.class, type[1] + "_" + hardened_clay[1]);
		GameRegistry.registerBlock((new BlockCompressedClayHardenedStained(type_num[1], hardened_clay_stained[2], Material.rock)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 1.25F)).setResistance((float) (Math.pow(8, type_num[1]) * 7.0F)).setStepSound(Block.soundTypePiston).setBlockName(hardened_clay_stained[1]).setBlockTextureName(modid + ":" + type[1] + "/" + hardened_clay_stained[0]), ItemBlockCompressedWithMetadata.class, type[1] + "_" + hardened_clay_stained[1]);
		GameRegistry.registerBlock((new BlockCompressed(type_num[1], brick + "_block", Material.rock)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 2.0F)).setResistance((float) (Math.pow(8, type_num[1]) * 10.0F)).setStepSound(Block.soundTypePiston).setBlockName(brick).setBlockTextureName(modid + ":" + type[1] + "/" + brick), ItemBlockCompressed.class, type[1] + "_" + brick);
		GameRegistry.registerBlock((new BlockCompressed(type_num[1], coal_block[0], Material.rock)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 50.0F)).setResistance((float) (Math.pow(8, type_num[1]) * 10.0F)).setStepSound(Block.soundTypePiston).setBlockName(coal_block[1]).setBlockTextureName(modid + ":" + type[1] + "/" + coal_block[0]), ItemBlockCompressed.class, type[1] + "_" + coal_block[1]);
		GameRegistry.registerBlock((new BlockCompressedCompressed(type_num[1], iron_block[0], MapColor.ironColor)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 5.0F)).setResistance((float) (Math.pow(8, type_num[1]) * 10.0F)).setStepSound(Block.soundTypeMetal).setBlockName(iron_block[1]).setBlockTextureName(modid + ":" + type[1] + "/" + iron_block[0]), ItemBlockCompressed.class, type[1] + "_" + iron_block[1]);
		GameRegistry.registerBlock((new BlockCompressedCompressed(type_num[1], gold_block[0], MapColor.goldColor)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 3.0F)).setResistance((float) (Math.pow(8, type_num[1]) * 10.0F)).setStepSound(Block.soundTypeMetal).setBlockName(gold_block[1]).setBlockTextureName(modid + ":" + type[1] + "/" + gold_block[0]), ItemBlockCompressed.class, type[1] + "_" + gold_block[1]);
		GameRegistry.registerBlock((new BlockCompressedCompressed(type_num[1], diamond_block[0], MapColor.diamondColor)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 5.0F)).setResistance((float) (Math.pow(8, type_num[1]) * 10.0F)).setStepSound(Block.soundTypeMetal).setBlockName(diamond_block[1]).setBlockTextureName(modid + ":" + type[1] + "/" + diamond_block[0]), ItemBlockCompressed.class, type[1] + "_" + diamond_block[1]);
		GameRegistry.registerBlock((new BlockCompressedCompressed(type_num[1], lapis_block[0], MapColor.lapisColor)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 3.0F)).setResistance((float) (Math.pow(8, type_num[1]) * 5.0F)).setStepSound(Block.soundTypePiston).setBlockName(lapis_block[1]).setBlockTextureName(modid + ":" + type[1] + "/" + lapis_block[0]), ItemBlockCompressed.class, type[1] + "_" + lapis_block[1]);
		GameRegistry.registerBlock((new BlockCompressedCompressed(type_num[1], emerald_block[0], MapColor.emeraldColor)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 5.0F)).setResistance((float) (Math.pow(8, type_num[1]) * 10.0F)).setStepSound(Block.soundTypeMetal).setBlockName(emerald_block[1]).setBlockTextureName(modid + ":" + type[1] + "/" + emerald_block[0]), ItemBlockCompressed.class, type[1] + "_" + emerald_block[1]);
		GameRegistry.registerBlock((new BlockCompressedCompressedPowered(type_num[1],redstone_block[0], MapColor.tntColor)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 5.0F)).setResistance((float) (Math.pow(8, type_num[1]) * 10.0F)).setStepSound(Block.soundTypeMetal).setBlockName(redstone_block[1]).setBlockTextureName(modid + ":" + type[1] + "/" + redstone_block[0]), ItemBlockCompressed.class, type[1] + "_" + redstone_block[1]);
		GameRegistry.registerBlock((new BlockCompressedOre(type_num[1], coal_ore[0], Material.rock)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 3.0F)).setResistance((float) (Math.pow(8, type_num[1]) * 5.0F)).setStepSound(Block.soundTypePiston).setBlockName(coal_ore[1]).setBlockTextureName(modid + ":" + type[1] + "/" + coal_ore[0]), ItemBlockCompressed.class, type[1] + "_" + coal_ore[1]);
		GameRegistry.registerBlock((new BlockCompressedOre(type_num[1], iron_ore[0], Material.rock)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 3.0F)).setResistance((float) (Math.pow(8, type_num[1]) * 5.0F)).setStepSound(Block.soundTypePiston).setBlockName(iron_ore[1]).setBlockTextureName(modid + ":" + type[1] + "/" + iron_ore[0]), ItemBlockCompressed.class, type[1] + "_" + iron_ore[1]);
		GameRegistry.registerBlock((new BlockCompressedOre(type_num[1], gold_ore[0], Material.rock)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 3.0F)).setResistance((float) (Math.pow(8, type_num[1]) * 5.0F)).setStepSound(Block.soundTypePiston).setBlockName(gold_ore[1]).setBlockTextureName(modid + ":" + type[1] + "/" + gold_ore[0]), ItemBlockCompressed.class, type[1] + "_" + gold_ore[1]);
		GameRegistry.registerBlock((new BlockCompressedOre(type_num[1], diamond_ore[0], Material.rock)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 3.0F)).setResistance((float) (Math.pow(8, type_num[1]) * 5.0F)).setStepSound(Block.soundTypePiston).setBlockName(diamond_ore[1]).setBlockTextureName(modid + ":" + type[1] + "/" + diamond_ore[0]), ItemBlockCompressed.class, type[1] + "_" + diamond_ore[1]);
		GameRegistry.registerBlock((new BlockCompressedOre(type_num[1], lapis_ore[0], Material.rock)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 3.0F)).setResistance((float) (Math.pow(8, type_num[1]) * 5.0F)).setStepSound(Block.soundTypePiston).setBlockName(lapis_ore[1]).setBlockTextureName(modid + ":" + type[1] + "/" + lapis_ore[0]), ItemBlockCompressed.class, type[1] + "_" + lapis_ore[1]);
		GameRegistry.registerBlock((new BlockCompressedOre(type_num[1], emerald_ore[0], Material.rock)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 3.0F)).setResistance((float) (Math.pow(8, type_num[1]) * 5.0F)).setStepSound(Block.soundTypePiston).setBlockName(emerald_ore[1]).setBlockTextureName(modid + ":" + type[1] + "/" + emerald_ore[0]), ItemBlockCompressed.class, type[1] + "_" + emerald_ore[1]);
		GameRegistry.registerBlock((new BlockCompressedRedstoneOre(type_num[1], redstone_ore[0], Material.rock, false)).setCreativeTab(tab_lc_block).setHardness((float) (Math.pow(8, type_num[1]) * 3.0F)).setResistance((float) (Math.pow(8, type_num[1]) * 5.0F)).setStepSound(Block.soundTypePiston).setBlockName(redstone_ore[1]).setBlockTextureName(modid + ":" + type[1] + "/" + redstone_ore[0]), ItemBlockCompressed.class, type[1] + "_" + redstone_ore[1]);
		GameRegistry.registerBlock((new BlockCompressedRedstoneOre(type_num[1], "lit_" + redstone_ore[0], Material.rock, true)).setLightLevel(type_num[1] * 0.125F + 0.625F).setHardness((float) (Math.pow(8, type_num[1]) * 3.0F)).setResistance((float) (Math.pow(8, type_num[1]) * 5.0F)).setStepSound(Block.soundTypePiston).setBlockName(redstone_ore[1]).setBlockTextureName(modid + ":" + type[1] + "/" + redstone_ore[0]), ItemBlockCompressed.class, type[1] + "_lit_" + redstone_ore[1]);
		

		
		/** New creative tab for medium compressed blocks */
		CreativeTabs tab_mc_block = new CreativeTabs("tab_" + type[2] + "_blocks")
		{
			public Item getTabIconItem()
			{
				return Item.getItemFromBlock(GameRegistry.findBlock(modid, type[2] + "_blockGold"));
			}
		};
		
		/** Registration medium compressed blocks */
		GameRegistry.registerBlock((new BlockCompressed(type_num[2], bedrock, Material.rock)).setCreativeTab(tab_mc_block).setBlockUnbreakable().setResistance((float) (Math.pow(8, type_num[2]) * 6000000.0F)).setStepSound(Block.soundTypePiston).setBlockName(bedrock).setBlockTextureName(modid + ":" + type[2] + "/" + bedrock), ItemBlockCompressed.class, type[2] + "_" + bedrock);
		GameRegistry.registerBlock((new BlockCompressedStoneBrick(type_num[2], stonebrick)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 1.5F)).setResistance((float) (Math.pow(8, type_num[2]) * 10.0F)).setStepSound(Block.soundTypePiston).setBlockName(stonebrick + "smooth").setBlockTextureName(modid + ":" + type[2] + "/" + stonebrick), ItemBlockCompressedWithMetadata.class, type[2] + "_" + stonebrick + "smooth");
		GameRegistry.registerBlock((new BlockCompressedStone(type_num[2], stone, Material.rock)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 1.5F)).setResistance((float) (Math.pow(8, type_num[2]) * 10.0F)).setStepSound(Block.soundTypePiston).setBlockName(stone).setBlockTextureName(modid + ":" + type[2] + "/" + stone), ItemBlockCompressed.class, type[2] + "_" + stone);
		GameRegistry.registerBlock((new BlockCompressed(type_num[2], cobblestone[0], Material.rock)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 2.0F)).setResistance((float) (Math.pow(8, type_num[2]) * 80.0F)).setStepSound(Block.soundTypePiston).setBlockName(cobblestone[1]).setBlockTextureName(modid + ":" + type[2] + "/" + cobblestone[0]), ItemBlockCompressed.class, type[2] + "_" + cobblestone[1]);
		GameRegistry.registerBlock((new BlockCompressed(type_num[2], cobblestone_mossy[0], Material.rock)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 2.0F)).setResistance((float) (Math.pow(8, type_num[2]) * 10.0F)).setStepSound(Block.soundTypePiston).setBlockName(cobblestone_mossy[1]).setBlockTextureName(modid + ":" + type[2] + "/" + cobblestone_mossy[2]), ItemBlockCompressed.class, type[2] + "_" + cobblestone_mossy[1]);
		GameRegistry.registerBlock((new BlockCompressedGravel(type_num[2], gravel)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 0.6F)).setStepSound(Block.soundTypeGravel).setBlockName(gravel).setBlockTextureName(modid + ":" + type[2] + "/" + gravel), ItemBlockCompressed.class, type[2] + "_" + gravel);
		GameRegistry.registerBlock((new BlockCompressedDirt(type_num[2], dirt, Material.ground)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 0.5F)).setStepSound(Block.soundTypeGravel).setBlockName(dirt + ".default").setBlockTextureName(modid + ":" + type[2] + "/" + dirt), ItemBlockCompressed.class, type[2] + "_" + dirt + ".default");
		GameRegistry.registerBlock((new BlockCompressedSand(type_num[2], modid + ":" + type[2] + "/")).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 0.5F)).setStepSound(Block.soundTypeSand).setBlockName(sand).setBlockTextureName(modid + ":" + type[2] + "/" + sand), ItemBlockCompressedWithMetadata.class, type[2] + "_" + sand);
		GameRegistry.registerBlock((new BlockCompressedSandStone(type_num[2], sandstone[0], Material.rock)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 0.8F)).setStepSound(Block.soundTypePiston).setBlockName(sandstone[1]).setBlockTextureName(modid + ":" + type[2] + "/" + sandstone[0]), ItemBlockCompressedWithMetadata.class, type[2] + "_" + sandstone[1]);
		GameRegistry.registerBlock((new BlockCompressed(type_num[2], end_stone[0], Material.rock)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 3.0F)).setResistance((float) (Math.pow(8, type_num[2]) * 15.0F)).setStepSound(Block.soundTypePiston).setBlockName(end_stone[1]).setBlockTextureName(modid + ":" + type[2] + "/" + end_stone[0]), ItemBlockCompressed.class, type[2] + "_" + end_stone[1]);
		GameRegistry.registerBlock((new BlockCompressedWood(type_num[2], wood[1])).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 2.0F)).setResistance((float) (Math.pow(8, type_num[2]) * 5.0F)).setStepSound(Block.soundTypeWood).setBlockName(wood[0]).setBlockTextureName(modid + ":" + type[2] + "/" + wood[1]), ItemBlockCompressedWithMetadata.class, type[2] + "_" + wood[0]);
		GameRegistry.registerBlock((new BlockCompressedBookshelf(type_num[2], bookshelf, Material.wood)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 1.5F)).setStepSound(Block.soundTypeWood).setBlockName(bookshelf).setBlockTextureName(modid + ":" + type[2] + "/" + bookshelf), ItemBlockCompressed.class, type[2] + "_" + bookshelf);
		GameRegistry.registerBlock((new BlockCompressedOldLog(type_num[2], log, Material.wood)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 2.0F)).setStepSound(Block.soundTypeWood).setBlockName(log).setBlockTextureName(modid + ":" + type[2] + "/" + log), ItemBlockCompressedWithMetadata.class, type[2] + "_" + log);
		GameRegistry.registerBlock((new BlockCompressedNewLog(type_num[2], log + "2", Material.wood)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 2.0F)).setStepSound(Block.soundTypeWood).setBlockName(log).setBlockTextureName(modid + ":" + type[2] + "/" + log), ItemBlockCompressedWithMetadata.class, type[2] + "_" + log + "2");
		GameRegistry.registerBlock((new BlockCompressedPumpkin(type_num[2], pumpkin, Material.gourd, false)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 1.0F)).setStepSound(Block.soundTypeWood).setBlockName(pumpkin).setBlockTextureName(modid + ":" + type[2] + "/" + pumpkin), ItemBlockCompressed.class, type[2] + "_" + pumpkin);
		GameRegistry.registerBlock((new BlockCompressedPumpkin(type_num[2], "lit_" + pumpkin, Material.gourd, true)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 1.0F)).setLightLevel(1.0F).setStepSound(Block.soundTypeWood).setBlockName("lit" + pumpkin).setBlockTextureName(modid + ":" + type[2] + "/" + pumpkin), ItemBlockCompressed.class, type[2] + "_lit" + pumpkin);
		GameRegistry.registerBlock((new BlockCompressedMelon(type_num[2], melon, Material.gourd)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 1.0F)).setStepSound(Block.soundTypeWood).setBlockName(melon).setBlockTextureName(modid + ":" + type[2] + "/" + melon), ItemBlockCompressed.class, type[2] + "_" + melon);
		GameRegistry.registerBlock((new BlockCompressedSponge(type_num[2], sponge, Material.sponge)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 0.6F)).setStepSound(Block.soundTypeGrass).setBlockName(sponge).setBlockTextureName(modid + ":" + type[2] + "/" + sponge), ItemBlockCompressed.class, type[2] + "_" + sponge);
		GameRegistry.registerBlock((new BlockCompressedGlass(type_num[2], modid + ":" + type[2] + "/" + glass, Material.glass, false)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 0.3F)).setStepSound(Block.soundTypeGlass).setBlockName(glass).setBlockTextureName(modid + ":" + type[2] + "/" + glass), ItemBlockCompressed.class, type[2] + "_" + glass);
		GameRegistry.registerBlock((new BlockCompressedStainedGlass(type_num[2], stained_glass[2], Material.glass)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 0.3F)).setStepSound(Block.soundTypeGlass).setBlockName(stained_glass[1]).setBlockTextureName(modid + ":" + type[2] + "/" + stained_glass[2]), ItemBlockCompressedWithMetadata.class, type[2] + "_" + stained_glass[1]);
		GameRegistry.registerBlock((new BlockCompressedWool(type_num[2],wool[0], Material.cloth)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 0.6F)).setStepSound(Block.soundTypeCloth).setBlockName(wool[1]).setBlockTextureName(modid + ":" + type[2] + "/" + wool[0] + "_colored"), ItemBlockCompressedWithMetadata.class, type[2] + "_" + wool[1]);
		GameRegistry.registerBlock((new BlockCompressedTNT(type_num[2], tnt, Material.tnt)).setCreativeTab(tab_mc_block).setHardness(0.0F).setStepSound(Block.soundTypeGrass).setBlockName(tnt).setBlockTextureName(modid + ":" + type[2] + "/" + tnt), ItemBlockCompressed.class, type[2] + "_" + tnt);
		GameRegistry.registerBlock((new BlockCompressedRedstoneLight(type_num[2], redstone_lamp[0], Material.redstoneLight, false)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 0.3F)).setStepSound(Block.soundTypeGlass).setBlockName(redstone_lamp[1]).setBlockTextureName(modid + ":" + type[2] + "/" + redstone_lamp[0] + "_off"), ItemBlockCompressed.class, type[2] + "_" + redstone_lamp[1]);
		GameRegistry.registerBlock((new BlockCompressedRedstoneLight(type_num[2], "lit_" + redstone_lamp[0], Material.redstoneLight, true)).setHardness((float) (Math.pow(8, type_num[2]) * 0.3F)).setStepSound(Block.soundTypeGlass).setBlockName(redstone_lamp[1]).setBlockTextureName(modid + ":" + type[2] + "/" + redstone_lamp[0] + "_on"), ItemBlockCompressed.class, type[2] + "_lit_" + redstone_lamp[1]);
		GameRegistry.registerBlock((new BlockCompressedGlowstone(type_num[2], glowstone[0], Material.glass)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 0.3F)).setStepSound(Block.soundTypeGlass).setLightLevel(1.0F).setBlockName(glowstone[1]).setBlockTextureName(modid + ":" + type[2] + "/" + glowstone[0]), ItemBlockCompressed.class, type[2] + "_" + glowstone[1]);
		GameRegistry.registerBlock((new BlockCompressedSoulSand(type_num[2], soul_sand[0], Material.sand)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 0.5F)).setStepSound(Block.soundTypeSand).setBlockName(soul_sand[1]).setBlockTextureName(modid + ":" + type[2] + "/" + soul_sand[0]), ItemBlockCompressed.class, type[2] + "_" + soul_sand[1]);
		GameRegistry.registerBlock((new BlockCompressedObsidian(type_num[2], obsidian, Material.rock)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 50.0F)).setResistance((float) (Math.pow(8, type_num[2]) * 2000.0F)).setStepSound(Block.soundTypePiston).setBlockName(obsidian).setBlockTextureName(modid + ":" + type[2] + "/" + obsidian), ItemBlockCompressed.class, type[2] + "_" + obsidian);
		GameRegistry.registerBlock((new BlockCompressed(type_num[2], nether_brick[0], Material.rock)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 2.0F)).setResistance((float) (Math.pow(8, type_num[2]) * 10.0F)).setStepSound(Block.soundTypePiston).setBlockName(nether_brick[1]).setBlockTextureName(modid + ":" + type[2] + "/" + nether_brick[0]), ItemBlockCompressed.class, type[2] + "_" + nether_brick[1]);
		GameRegistry.registerBlock((new BlockCompressedNetherrack(type_num[2], netherrack[0], Material.rock)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 0.4F)).setStepSound(Block.soundTypePiston).setBlockName(netherrack[1]).setBlockTextureName(modid + ":" + type[2] + "/" + netherrack[0]), ItemBlockCompressed.class, type[2] + "_" + netherrack[1]);
		GameRegistry.registerBlock((new BlockCompressedOre(type_num[2], quartz_ore[0], Material.rock)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 3.0F)).setResistance((float) (Math.pow(8, type_num[2]) * 5.0F)).setStepSound(Block.soundTypePiston).setBlockName(quartz_ore[1]).setBlockTextureName(modid + ":" + type[2] + "/" + quartz_ore[0]), ItemBlockCompressed.class, type[2] + "_" + quartz_ore[1]);
		GameRegistry.registerBlock((new BlockCompressedQuartz(type_num[2], quartz_block[0], Material.rock)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 0.8F)).setStepSound(Block.soundTypePiston).setBlockName(quartz_block[1]).setBlockTextureName(modid + ":" + type[2] + "/" + quartz_block[0]), ItemBlockCompressedWithMetadata.class, type[2] + "_" + quartz_block[1]);
		GameRegistry.registerBlock((new BlockCompressedSnowBlock(type_num[2], snow, Material.craftedSnow)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 0.2F)).setStepSound(Block.soundTypeSnow).setBlockName(snow).setBlockTextureName(modid + ":" + type[2] + "/" + snow), ItemBlockCompressed.class, type[2] + "_" + snow);
		GameRegistry.registerBlock((new BlockCompressedIce(type_num[2], modid + ":" + type[2] + "/" + ice, Material.ice)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 0.5F)).setLightOpacity(6 - type_num[1] * 2).setStepSound(Block.soundTypeGlass).setBlockName(ice).setBlockTextureName(modid + ":" + type[2] + "/" + ice), ItemBlockCompressed.class, type[2] + "_" + ice);
		GameRegistry.registerBlock((new BlockCompressedPackedIce(type_num[2], ice_packed[0], Material.packedIce)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 0.5F)).setStepSound(Block.soundTypeGlass).setBlockName(ice_packed[1]).setBlockTextureName(modid + ":" + type[2] + "/" + ice_packed[2]), ItemBlockCompressed.class, type[2] + "_" + ice_packed[1]);
		GameRegistry.registerBlock((new BlockCompressedClay(type_num[2], clay, Material.clay)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 0.6F)).setStepSound(Block.soundTypeGravel).setBlockName(clay).setBlockTextureName(modid + ":" + type[2] + "/" + clay), ItemBlockCompressed.class, type[2] + "_" + clay);
		GameRegistry.registerBlock((new BlockCompressedClayHardened(type_num[2], hardened_clay[0], Material.rock)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 1.25F)).setResistance((float) (Math.pow(8, type_num[2]) * 7.0F)).setStepSound(Block.soundTypePiston).setBlockName(hardened_clay[1]).setBlockTextureName(modid + ":" + type[2] + "/" + hardened_clay[0]), ItemBlockCompressed.class, type[2] + "_" + hardened_clay[1]);
		GameRegistry.registerBlock((new BlockCompressedClayHardenedStained(type_num[2], hardened_clay_stained[2], Material.rock)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 1.25F)).setResistance((float) (Math.pow(8, type_num[2]) * 7.0F)).setStepSound(Block.soundTypePiston).setBlockName(hardened_clay_stained[1]).setBlockTextureName(modid + ":" + type[2] + "/" + hardened_clay_stained[0]), ItemBlockCompressedWithMetadata.class, type[2] + "_" + hardened_clay_stained[1]);
		GameRegistry.registerBlock((new BlockCompressed(type_num[2], brick + "_block", Material.rock)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 2.0F)).setResistance((float) (Math.pow(8, type_num[2]) * 10.0F)).setStepSound(Block.soundTypePiston).setBlockName(brick).setBlockTextureName(modid + ":" + type[2] + "/" + brick), ItemBlockCompressed.class, type[2] + "_" + brick);
		GameRegistry.registerBlock((new BlockCompressed(type_num[2], coal_block[0], Material.rock)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 50.0F)).setResistance((float) (Math.pow(8, type_num[2]) * 10.0F)).setStepSound(Block.soundTypePiston).setBlockName(coal_block[1]).setBlockTextureName(modid + ":" + type[2] + "/" + coal_block[0]), ItemBlockCompressed.class, type[2] + "_" + coal_block[1]);
		GameRegistry.registerBlock((new BlockCompressedCompressed(type_num[2], iron_block[0], MapColor.ironColor)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 5.0F)).setResistance((float) (Math.pow(8, type_num[2]) * 10.0F)).setStepSound(Block.soundTypeMetal).setBlockName(iron_block[1]).setBlockTextureName(modid + ":" + type[2] + "/" + iron_block[0]), ItemBlockCompressed.class, type[2] + "_" + iron_block[1]);
		GameRegistry.registerBlock((new BlockCompressedCompressed(type_num[2], gold_block[0], MapColor.goldColor)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 3.0F)).setResistance((float) (Math.pow(8, type_num[2]) * 10.0F)).setStepSound(Block.soundTypeMetal).setBlockName(gold_block[1]).setBlockTextureName(modid + ":" + type[2] + "/" + gold_block[0]), ItemBlockCompressed.class, type[2] + "_" + gold_block[1]);
		GameRegistry.registerBlock((new BlockCompressedCompressed(type_num[2], diamond_block[0], MapColor.diamondColor)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 5.0F)).setResistance((float) (Math.pow(8, type_num[2]) * 10.0F)).setStepSound(Block.soundTypeMetal).setBlockName(diamond_block[1]).setBlockTextureName(modid + ":" + type[2] + "/" + diamond_block[0]), ItemBlockCompressed.class, type[2] + "_" + diamond_block[1]);
		GameRegistry.registerBlock((new BlockCompressedCompressed(type_num[2], lapis_block[0], MapColor.lapisColor)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 3.0F)).setResistance((float) (Math.pow(8, type_num[2]) * 5.0F)).setStepSound(Block.soundTypePiston).setBlockName(lapis_block[1]).setBlockTextureName(modid + ":" + type[2] + "/" + lapis_block[0]), ItemBlockCompressed.class, type[2] + "_" + lapis_block[1]);
		GameRegistry.registerBlock((new BlockCompressedCompressed(type_num[2], emerald_block[0], MapColor.emeraldColor)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 5.0F)).setResistance((float) (Math.pow(8, type_num[2]) * 10.0F)).setStepSound(Block.soundTypeMetal).setBlockName(emerald_block[1]).setBlockTextureName(modid + ":" + type[2] + "/" + emerald_block[0]), ItemBlockCompressed.class, type[2] + "_" + emerald_block[1]);
		GameRegistry.registerBlock((new BlockCompressedCompressedPowered(type_num[2], redstone_block[0], MapColor.tntColor)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 5.0F)).setResistance((float) (Math.pow(8, type_num[2]) * 10.0F)).setStepSound(Block.soundTypeMetal).setBlockName(redstone_block[1]).setBlockTextureName(modid + ":" + type[2] + "/" + redstone_block[0]), ItemBlockCompressed.class, type[2] + "_" + redstone_block[1]);
		GameRegistry.registerBlock((new BlockCompressedOre(type_num[2], coal_ore[0], Material.rock)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 3.0F)).setResistance((float) (Math.pow(8, type_num[2]) * 5.0F)).setStepSound(Block.soundTypePiston).setBlockName(coal_ore[1]).setBlockTextureName(modid + ":" + type[2] + "/" + coal_ore[0]), ItemBlockCompressed.class, type[2] + "_" + coal_ore[1]);
		GameRegistry.registerBlock((new BlockCompressedOre(type_num[2], iron_ore[0], Material.rock)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 3.0F)).setResistance((float) (Math.pow(8, type_num[2]) * 5.0F)).setStepSound(Block.soundTypePiston).setBlockName(iron_ore[1]).setBlockTextureName(modid + ":" + type[2] + "/" + iron_ore[0]), ItemBlockCompressed.class, type[2] + "_" + iron_ore[1]);
		GameRegistry.registerBlock((new BlockCompressedOre(type_num[2], gold_ore[0], Material.rock)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 3.0F)).setResistance((float) (Math.pow(8, type_num[2]) * 5.0F)).setStepSound(Block.soundTypePiston).setBlockName(gold_ore[1]).setBlockTextureName(modid + ":" + type[2] + "/" + gold_ore[0]), ItemBlockCompressed.class, type[2] + "_" + gold_ore[1]);
		GameRegistry.registerBlock((new BlockCompressedOre(type_num[2], diamond_ore[0], Material.rock)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 3.0F)).setResistance((float) (Math.pow(8, type_num[2]) * 5.0F)).setStepSound(Block.soundTypePiston).setBlockName(diamond_ore[1]).setBlockTextureName(modid + ":" + type[2] + "/" + diamond_ore[0]), ItemBlockCompressed.class, type[2] + "_" + diamond_ore[1]);
		GameRegistry.registerBlock((new BlockCompressedOre(type_num[2], lapis_ore[0], Material.rock)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 3.0F)).setResistance((float) (Math.pow(8, type_num[2]) * 5.0F)).setStepSound(Block.soundTypePiston).setBlockName(lapis_ore[1]).setBlockTextureName(modid + ":" + type[2] + "/" + lapis_ore[0]), ItemBlockCompressed.class, type[2] + "_" + lapis_ore[1]);
		GameRegistry.registerBlock((new BlockCompressedOre(type_num[2], emerald_ore[0], Material.rock)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 3.0F)).setResistance((float) (Math.pow(8, type_num[2]) * 5.0F)).setStepSound(Block.soundTypePiston).setBlockName(emerald_ore[1]).setBlockTextureName(modid + ":" + type[2] + "/" + emerald_ore[0]), ItemBlockCompressed.class, type[2] + "_" + emerald_ore[1]);
		GameRegistry.registerBlock((new BlockCompressedRedstoneOre(type_num[2], redstone_ore[0], Material.rock, false)).setCreativeTab(tab_mc_block).setHardness((float) (Math.pow(8, type_num[2]) * 3.0F)).setResistance((float) (Math.pow(8, type_num[2]) * 5.0F)).setStepSound(Block.soundTypePiston).setBlockName(redstone_ore[1]).setBlockTextureName(modid + ":" + type[2] + "/" + redstone_ore[0]), ItemBlockCompressed.class, type[2] + "_" + redstone_ore[1]);
		GameRegistry.registerBlock((new BlockCompressedRedstoneOre(type_num[2], "lit_" + redstone_ore[0], Material.rock, true)).setLightLevel(type_num[2] * 0.125F + 0.625F).setHardness((float) (Math.pow(8, type_num[2]) * 3.0F)).setResistance((float) (Math.pow(8, type_num[2]) * 5.0F)).setStepSound(Block.soundTypePiston).setBlockName(redstone_ore[1]).setBlockTextureName(modid + ":" + type[2] + "/" + redstone_ore[0]), ItemBlockCompressed.class, type[2] + "_lit_" + redstone_ore[1]);
			
		/** New creative tab for high compressed blocks */
		CreativeTabs tab_hc_block = new CreativeTabs("tab_" + type[3] + "_blocks")
		{
			public Item getTabIconItem()
			{
				return Item.getItemFromBlock(GameRegistry.findBlock(modid, type[3] + "_blockDiamond"));
			}
		};
		
		/** Registration high compressed blocks */
		GameRegistry.registerBlock((new BlockCompressed(type_num[3], bedrock, Material.rock)).setCreativeTab(tab_hc_block).setBlockUnbreakable().setResistance((float) (Math.pow(8, type_num[3]) * 6000000.0F)).setStepSound(Block.soundTypePiston).setBlockName(bedrock).setBlockTextureName(modid + ":" + type[3] + "/" + bedrock), ItemBlockCompressed.class, type[3] + "_" + bedrock);
		GameRegistry.registerBlock((new BlockCompressedStoneBrick(type_num[3], stonebrick)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 1.5F)).setResistance((float) (Math.pow(8, type_num[3]) * 10.0F)).setStepSound(Block.soundTypePiston).setBlockName(stonebrick + "smooth").setBlockTextureName(modid + ":" + type[3] + "/" + stonebrick), ItemBlockCompressedWithMetadata.class, type[3] + "_" + stonebrick + "smooth");
		GameRegistry.registerBlock((new BlockCompressedStone(type_num[3], stone, Material.rock)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 1.5F)).setResistance((float) (Math.pow(8, type_num[3]) * 10.0F)).setStepSound(Block.soundTypePiston).setBlockName(stone).setBlockTextureName(modid + ":" + type[3] + "/" + stone), ItemBlockCompressed.class, type[3] + "_" + stone);
		GameRegistry.registerBlock((new BlockCompressed(type_num[3], cobblestone[0], Material.rock)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 2.0F)).setResistance((float) (Math.pow(8, type_num[3]) * 80.0F)).setStepSound(Block.soundTypePiston).setBlockName(cobblestone[1]).setBlockTextureName(modid + ":" + type[3] + "/" + cobblestone[0]), ItemBlockCompressed.class, type[3] + "_" + cobblestone[1]);
		GameRegistry.registerBlock((new BlockCompressed(type_num[3], cobblestone_mossy[0], Material.rock)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 2.0F)).setResistance((float) (Math.pow(8, type_num[3]) * 10.0F)).setStepSound(Block.soundTypePiston).setBlockName(cobblestone_mossy[1]).setBlockTextureName(modid + ":" + type[3] + "/" + cobblestone_mossy[2]), ItemBlockCompressed.class, type[3] + "_" + cobblestone_mossy[1]);
		GameRegistry.registerBlock((new BlockCompressedGravel(type_num[3], gravel)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 0.6F)).setStepSound(Block.soundTypeGravel).setBlockName(gravel).setBlockTextureName(modid + ":" + type[3] + "/" + gravel), ItemBlockCompressed.class, type[3] + "_" + gravel);
		GameRegistry.registerBlock((new BlockCompressedDirt(type_num[3], dirt, Material.ground)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 0.5F)).setStepSound(Block.soundTypeGravel).setBlockName(dirt + ".default").setBlockTextureName(modid + ":" + type[3] + "/" + dirt), ItemBlockCompressed.class, type[3] + "_" + dirt + ".default");
		GameRegistry.registerBlock((new BlockCompressedSand(type_num[3],modid + ":" + type[3] + "/")).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 0.5F)).setStepSound(Block.soundTypeSand).setBlockName(sand).setBlockTextureName(modid + ":" + type[3] + "/" + sand), ItemBlockCompressedWithMetadata.class, type[3] + "_" + sand);
		GameRegistry.registerBlock((new BlockCompressedSandStone(type_num[3], sandstone[0], Material.rock)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 0.8F)).setStepSound(Block.soundTypePiston).setBlockName(sandstone[1]).setBlockTextureName(modid + ":" + type[3] + "/" + sandstone[0]), ItemBlockCompressedWithMetadata.class, type[3] + "_" + sandstone[1]);
		GameRegistry.registerBlock((new BlockCompressed(type_num[3], end_stone[0], Material.rock)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 3.0F)).setResistance((float) (Math.pow(8, type_num[3]) * 15.0F)).setStepSound(Block.soundTypePiston).setBlockName(end_stone[1]).setBlockTextureName(modid + ":" + type[3] + "/" + end_stone[0]), ItemBlockCompressed.class, type[3] + "_" + end_stone[1]);
		GameRegistry.registerBlock((new BlockCompressedWood(type_num[3], wood[1])).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 2.0F)).setResistance((float) (Math.pow(8, type_num[3]) * 5.0F)).setStepSound(Block.soundTypeWood).setBlockName(wood[0]).setBlockTextureName(modid + ":" + type[3] + "/" + wood[1]), ItemBlockCompressedWithMetadata.class, type[3] + "_" + wood[0]);
		GameRegistry.registerBlock((new BlockCompressedBookshelf(type_num[3], bookshelf, Material.wood)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 1.5F)).setStepSound(Block.soundTypeWood).setBlockName(bookshelf).setBlockTextureName(modid + ":" + type[3] + "/" + bookshelf), ItemBlockCompressed.class, type[3] + "_" + bookshelf);
		GameRegistry.registerBlock((new BlockCompressedOldLog(type_num[3], log, Material.wood)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 2.0F)).setStepSound(Block.soundTypeWood).setBlockName(log).setBlockTextureName(modid + ":" + type[3] + "/" + log), ItemBlockCompressedWithMetadata.class, type[3] + "_" + log);
		GameRegistry.registerBlock((new BlockCompressedNewLog(type_num[3], log + "2", Material.wood)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 2.0F)).setStepSound(Block.soundTypeWood).setBlockName(log).setBlockTextureName(modid + ":" + type[3] + "/" + log), ItemBlockCompressedWithMetadata.class, type[3] + "_" + log + "2");
		GameRegistry.registerBlock((new BlockCompressedPumpkin(type_num[3], pumpkin, Material.gourd, false)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 1.0F)).setStepSound(Block.soundTypeWood).setBlockName(pumpkin).setBlockTextureName(modid + ":" + type[3] + "/" + pumpkin), ItemBlockCompressed.class, type[3] + "_" + pumpkin);
		GameRegistry.registerBlock((new BlockCompressedPumpkin(type_num[3], "lit_" + pumpkin, Material.gourd, true)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 1.0F)).setLightLevel(1.0F).setStepSound(Block.soundTypeWood).setBlockName("lit" + pumpkin).setBlockTextureName(modid + ":" + type[3] + "/" + pumpkin), ItemBlockCompressed.class, type[3] + "_lit" + pumpkin);
		GameRegistry.registerBlock((new BlockCompressedMelon(type_num[3], melon, Material.gourd)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 1.0F)).setStepSound(Block.soundTypeWood).setBlockName(melon).setBlockTextureName(modid + ":" + type[3] + "/" + melon), ItemBlockCompressed.class, type[3] + "_" + melon);
		GameRegistry.registerBlock((new BlockCompressedSponge(type_num[3], sponge, Material.sponge)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 0.6F)).setStepSound(Block.soundTypeGrass).setBlockName(sponge).setBlockTextureName(modid + ":" + type[3] + "/" + sponge), ItemBlockCompressed.class, type[3] + "_" + sponge);
		GameRegistry.registerBlock((new BlockCompressedGlass(type_num[3], modid + ":" + type[3] + "/" + glass, Material.glass, false)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 0.3F)).setStepSound(Block.soundTypeGlass).setBlockName(glass).setBlockTextureName(modid + ":" + type[3] + "/" + glass), ItemBlockCompressed.class, type[3] + "_" + glass);
		GameRegistry.registerBlock((new BlockCompressedStainedGlass(type_num[3], stained_glass[2], Material.glass)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 0.3F)).setStepSound(Block.soundTypeGlass).setBlockName(stained_glass[1]).setBlockTextureName(modid + ":" + type[3] + "/" + stained_glass[2]), ItemBlockCompressedWithMetadata.class, type[3] + "_" + stained_glass[1]);
		GameRegistry.registerBlock((new BlockCompressedWool(type_num[3],wool[0], Material.cloth)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 0.6F)).setStepSound(Block.soundTypeCloth).setBlockName(wool[1]).setBlockTextureName(modid + ":" + type[3] + "/" + wool[0] + "_colored"), ItemBlockCompressedWithMetadata.class, type[3] + "_" + wool[1]);
		GameRegistry.registerBlock((new BlockCompressedTNT(type_num[3], tnt, Material.tnt)).setCreativeTab(tab_hc_block).setHardness(0.0F).setStepSound(Block.soundTypeGrass).setBlockName(tnt).setBlockTextureName(modid + ":" + type[3] + "/" + tnt), ItemBlockCompressed.class, type[3] + "_" + tnt);
		GameRegistry.registerBlock((new BlockCompressedRedstoneLight(type_num[3], redstone_lamp[0], Material.redstoneLight, false)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 0.3F)).setStepSound(Block.soundTypeGlass).setBlockName(redstone_lamp[1]).setBlockTextureName(modid + ":" + type[3] + "/" + redstone_lamp[0] + "_off"), ItemBlockCompressed.class, type[3] + "_" + redstone_lamp[1]);
		GameRegistry.registerBlock((new BlockCompressedRedstoneLight(type_num[3], "lit_" + redstone_lamp[0], Material.redstoneLight, true)).setHardness((float) (Math.pow(8, type_num[3]) * 0.3F)).setStepSound(Block.soundTypeGlass).setBlockName(redstone_lamp[1]).setBlockTextureName(modid + ":" + type[3] + "/" + redstone_lamp[0] + "_on"), ItemBlockCompressed.class, type[3] + "_lit_" + redstone_lamp[1]);
		GameRegistry.registerBlock((new BlockCompressedGlowstone(type_num[3], glowstone[0], Material.glass)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 0.3F)).setStepSound(Block.soundTypeGlass).setLightLevel(1.0F).setBlockName(glowstone[1]).setBlockTextureName(modid + ":" + type[3] + "/" + glowstone[0]), ItemBlockCompressed.class, type[3] + "_" + glowstone[1]);
		GameRegistry.registerBlock((new BlockCompressedSoulSand(type_num[3], soul_sand[0], Material.sand)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 0.5F)).setStepSound(Block.soundTypeSand).setBlockName(soul_sand[1]).setBlockTextureName(modid + ":" + type[3] + "/" + soul_sand[0]), ItemBlockCompressed.class, type[3] + "_" + soul_sand[1]);
		GameRegistry.registerBlock((new BlockCompressedObsidian(type_num[3], obsidian, Material.rock)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 50.0F)).setResistance((float) (Math.pow(8, type_num[3]) * 2000.0F)).setStepSound(Block.soundTypePiston).setBlockName(obsidian).setBlockTextureName(modid + ":" + type[3] + "/" + obsidian), ItemBlockCompressed.class, type[3] + "_" + obsidian);
		GameRegistry.registerBlock((new BlockCompressed(type_num[3], nether_brick[0], Material.rock)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 2.0F)).setResistance((float) (Math.pow(8, type_num[3]) * 10.0F)).setStepSound(Block.soundTypePiston).setBlockName(nether_brick[1]).setBlockTextureName(modid + ":" + type[3] + "/" + nether_brick[0]), ItemBlockCompressed.class, type[3] + "_" + nether_brick[1]);
		GameRegistry.registerBlock((new BlockCompressedNetherrack(type_num[3], netherrack[0], Material.rock)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 0.4F)).setStepSound(Block.soundTypePiston).setBlockName(netherrack[1]).setBlockTextureName(modid + ":" + type[3] + "/" + netherrack[0]), ItemBlockCompressed.class, type[3] + "_" + netherrack[1]);
		GameRegistry.registerBlock((new BlockCompressedOre(type_num[3], quartz_ore[0], Material.rock)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 3.0F)).setResistance((float) (Math.pow(8, type_num[3]) * 5.0F)).setStepSound(Block.soundTypePiston).setBlockName(quartz_ore[1]).setBlockTextureName(modid + ":" + type[3] + "/" + quartz_ore[0]), ItemBlockCompressed.class, type[3] + "_" + quartz_ore[1]);
		GameRegistry.registerBlock((new BlockCompressedQuartz(type_num[3], quartz_block[0], Material.rock)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 0.8F)).setStepSound(Block.soundTypePiston).setBlockName(quartz_block[1]).setBlockTextureName(modid + ":" + type[3] + "/" + quartz_block[0]), ItemBlockCompressedWithMetadata.class, type[3] + "_" + quartz_block[1]);
		GameRegistry.registerBlock((new BlockCompressedSnowBlock(type_num[3], snow, Material.craftedSnow)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 0.2F)).setStepSound(Block.soundTypeSnow).setBlockName(snow).setBlockTextureName(modid + ":" + type[3] + "/" + snow), ItemBlockCompressed.class, type[3] + "_" + snow);
		GameRegistry.registerBlock((new BlockCompressedIce(type_num[3], modid + ":" + type[3] + "/" + ice, Material.ice)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 0.5F)).setLightOpacity(6 - type_num[1] * 2).setStepSound(Block.soundTypeGlass).setBlockName(ice).setBlockTextureName(modid + ":" + type[3] + "/" + ice), ItemBlockCompressed.class, type[3] + "_" + ice);
		GameRegistry.registerBlock((new BlockCompressedPackedIce(type_num[3], ice_packed[0], Material.packedIce)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 0.5F)).setStepSound(Block.soundTypeGlass).setBlockName(ice_packed[1]).setBlockTextureName(modid + ":" + type[3] + "/" + ice_packed[2]), ItemBlockCompressed.class, type[3] + "_" + ice_packed[1]);
		GameRegistry.registerBlock((new BlockCompressedClay(type_num[3], clay, Material.clay)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 0.6F)).setStepSound(Block.soundTypeGravel).setBlockName(clay).setBlockTextureName(modid + ":" + type[3] + "/" + clay), ItemBlockCompressed.class, type[3] + "_" + clay);
		GameRegistry.registerBlock((new BlockCompressedClayHardened(type_num[3], hardened_clay[0], Material.rock)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 1.25F)).setResistance((float) (Math.pow(8, type_num[3]) * 7.0F)).setStepSound(Block.soundTypePiston).setBlockName(hardened_clay[1]).setBlockTextureName(modid + ":" + type[3] + "/" + hardened_clay[0]), ItemBlockCompressed.class, type[3] + "_" + hardened_clay[1]);
		GameRegistry.registerBlock((new BlockCompressedClayHardenedStained(type_num[3], hardened_clay_stained[2], Material.rock)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 1.25F)).setResistance((float) (Math.pow(8, type_num[3]) * 7.0F)).setStepSound(Block.soundTypePiston).setBlockName(hardened_clay_stained[1]).setBlockTextureName(modid + ":" + type[3] + "/" + hardened_clay_stained[0]), ItemBlockCompressedWithMetadata.class, type[3] + "_" + hardened_clay_stained[1]);
		GameRegistry.registerBlock((new BlockCompressed(type_num[3], brick + "_block", Material.rock)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 2.0F)).setResistance((float) (Math.pow(8, type_num[3]) * 10.0F)).setStepSound(Block.soundTypePiston).setBlockName(brick).setBlockTextureName(modid + ":" + type[3] + "/" + brick), ItemBlockCompressed.class, type[3] + "_" + brick);
		GameRegistry.registerBlock((new BlockCompressed(type_num[3], coal_block[0], Material.rock)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 50.0F)).setResistance((float) (Math.pow(8, type_num[3]) * 10.0F)).setStepSound(Block.soundTypePiston).setBlockName(coal_block[1]).setBlockTextureName(modid + ":" + type[3] + "/" + coal_block[0]), ItemBlockCompressed.class, type[3] + "_" + coal_block[1]);
		GameRegistry.registerBlock((new BlockCompressedCompressed(type_num[3], iron_block[0], MapColor.ironColor)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 5.0F)).setResistance((float) (Math.pow(8, type_num[3]) * 10.0F)).setStepSound(Block.soundTypeMetal).setBlockName(iron_block[1]).setBlockTextureName(modid + ":" + type[3] + "/" + iron_block[0]), ItemBlockCompressed.class, type[3] + "_" + iron_block[1]);
		GameRegistry.registerBlock((new BlockCompressedCompressed(type_num[3], gold_block[0], MapColor.goldColor)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 3.0F)).setResistance((float) (Math.pow(8, type_num[3]) * 10.0F)).setStepSound(Block.soundTypeMetal).setBlockName(gold_block[1]).setBlockTextureName(modid + ":" + type[3] + "/" + gold_block[0]), ItemBlockCompressed.class, type[3] + "_" + gold_block[1]);
		GameRegistry.registerBlock((new BlockCompressedCompressed(type_num[3], diamond_block[0], MapColor.diamondColor)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 5.0F)).setResistance((float) (Math.pow(8, type_num[3]) * 10.0F)).setStepSound(Block.soundTypeMetal).setBlockName(diamond_block[1]).setBlockTextureName(modid + ":" + type[3] + "/" + diamond_block[0]), ItemBlockCompressed.class, type[3] + "_" + diamond_block[1]);
		GameRegistry.registerBlock((new BlockCompressedCompressed(type_num[3], lapis_block[0], MapColor.lapisColor)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 3.0F)).setResistance((float) (Math.pow(8, type_num[3]) * 5.0F)).setStepSound(Block.soundTypePiston).setBlockName(lapis_block[1]).setBlockTextureName(modid + ":" + type[3] + "/" + lapis_block[0]), ItemBlockCompressed.class, type[3] + "_" + lapis_block[1]);
		GameRegistry.registerBlock((new BlockCompressedCompressed(type_num[3], emerald_block[0], MapColor.emeraldColor)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 5.0F)).setResistance((float) (Math.pow(8, type_num[3]) * 10.0F)).setStepSound(Block.soundTypeMetal).setBlockName(emerald_block[1]).setBlockTextureName(modid + ":" + type[3] + "/" + emerald_block[0]), ItemBlockCompressed.class, type[3] + "_" + emerald_block[1]);
		GameRegistry.registerBlock((new BlockCompressedCompressedPowered(type_num[3], redstone_block[0], MapColor.tntColor)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 5.0F)).setResistance((float) (Math.pow(8, type_num[3]) * 10.0F)).setStepSound(Block.soundTypeMetal).setBlockName(redstone_block[1]).setBlockTextureName(modid + ":" + type[3] + "/" + redstone_block[0]), ItemBlockCompressed.class, type[3] + "_" + redstone_block[1]);
		GameRegistry.registerBlock((new BlockCompressedOre(type_num[3], coal_ore[0], Material.rock)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 3.0F)).setResistance((float) (Math.pow(8, type_num[3]) * 5.0F)).setStepSound(Block.soundTypePiston).setBlockName(coal_ore[1]).setBlockTextureName(modid + ":" + type[3] + "/" + coal_ore[0]), ItemBlockCompressed.class, type[3] + "_" + coal_ore[1]);
		GameRegistry.registerBlock((new BlockCompressedOre(type_num[3], iron_ore[0], Material.rock)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 3.0F)).setResistance((float) (Math.pow(8, type_num[3]) * 5.0F)).setStepSound(Block.soundTypePiston).setBlockName(iron_ore[1]).setBlockTextureName(modid + ":" + type[3] + "/" + iron_ore[0]), ItemBlockCompressed.class, type[3] + "_" + iron_ore[1]);
		GameRegistry.registerBlock((new BlockCompressedOre(type_num[3], gold_ore[0], Material.rock)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 3.0F)).setResistance((float) (Math.pow(8, type_num[3]) * 5.0F)).setStepSound(Block.soundTypePiston).setBlockName(gold_ore[1]).setBlockTextureName(modid + ":" + type[3] + "/" + gold_ore[0]), ItemBlockCompressed.class, type[3] + "_" + gold_ore[1]);
		GameRegistry.registerBlock((new BlockCompressedOre(type_num[3], diamond_ore[0], Material.rock)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 3.0F)).setResistance((float) (Math.pow(8, type_num[3]) * 5.0F)).setStepSound(Block.soundTypePiston).setBlockName(diamond_ore[1]).setBlockTextureName(modid + ":" + type[3] + "/" + diamond_ore[0]), ItemBlockCompressed.class, type[3] + "_" + diamond_ore[1]);
		GameRegistry.registerBlock((new BlockCompressedOre(type_num[3], lapis_ore[0], Material.rock)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 3.0F)).setResistance((float) (Math.pow(8, type_num[3]) * 5.0F)).setStepSound(Block.soundTypePiston).setBlockName(lapis_ore[1]).setBlockTextureName(modid + ":" + type[3] + "/" + lapis_ore[0]), ItemBlockCompressed.class, type[3] + "_" + lapis_ore[1]);
		GameRegistry.registerBlock((new BlockCompressedOre(type_num[3], emerald_ore[0], Material.rock)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 3.0F)).setResistance((float) (Math.pow(8, type_num[3]) * 5.0F)).setStepSound(Block.soundTypePiston).setBlockName(emerald_ore[1]).setBlockTextureName(modid + ":" + type[3] + "/" + emerald_ore[0]), ItemBlockCompressed.class, type[3] + "_" + emerald_ore[1]);
		GameRegistry.registerBlock((new BlockCompressedRedstoneOre(type_num[3], redstone_ore[0], Material.rock, false)).setCreativeTab(tab_hc_block).setHardness((float) (Math.pow(8, type_num[3]) * 3.0F)).setResistance((float) (Math.pow(8, type_num[3]) * 5.0F)).setStepSound(Block.soundTypePiston).setBlockName(redstone_ore[1]).setBlockTextureName(modid + ":" + type[3] + "/" + redstone_ore[0]), ItemBlockCompressed.class, type[3] + "_" + redstone_ore[1]);
		GameRegistry.registerBlock((new BlockCompressedRedstoneOre(type_num[3], "lit_" + redstone_ore[0], Material.rock, true)).setLightLevel(type_num[3] * 0.125F + 0.625F).setHardness((float) (Math.pow(8, type_num[3]) * 3.0F)).setResistance((float) (Math.pow(8, type_num[3]) * 5.0F)).setStepSound(Block.soundTypePiston).setBlockName(redstone_ore[1]).setBlockTextureName(modid + ":" + type[3] + "/" + redstone_ore[0]), ItemBlockCompressed.class, type[3] + "_lit_" + redstone_ore[1]);
	}
}